# Generated by Django 4.1.5 on 2023-07-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taskmodel_author_alter_taskmodel_id_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='author',
            field=models.CharField(max_length=150),
        ),
    ]
