# Generated by Django 4.1.5 on 2023-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_taskmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='fullnames',
            field=models.CharField(default='', max_length=100),
        ),
    ]
